#!/bin/bash
# This hook is sourced after a new virtualenv is activated.

proj_name=$(echo $VIRTUAL_ENV|awk -F'/' '{print $NF}')
proj_path=$PROJECT_HOME/$new_project_name

[ ! -d $proj_path ] && mkdir -p $proj_path
add2virtualenv $proj_path
cd $proj_path
